# Generated by Django 4.2.6 on 2023-10-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_customerprofile_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
