# Generated by Django 4.2.6 on 2023-10-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customerprofile_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='session_id',
        ),
    ]
