# Generated by Django 4.2.6 on 2023-10-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
