# Generated by Django 4.2.6 on 2023-10-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_favorites_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
    ]
